# Generated by Django 5.1.4 on 2025-01-26 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('vision', models.TextField()),
                ('time_horizon', models.DateField()),
                ('key_business_goals', models.JSONField(default=list)),
                ('key_organizational_goals', models.JSONField(default=list)),
                ('communication_leads', models.ManyToManyField(related_name='strategy_communication_leads', to=settings.AUTH_USER_MODEL)),
                ('executive_sponsors', models.ManyToManyField(related_name='strategy_executive_sponsors', to=settings.AUTH_USER_MODEL)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='flight_map.roadmap')),
                ('strategy_leads', models.ManyToManyField(related_name='strategy_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StrategicGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('business', 'Business Goal'), ('organizational', 'Organizational Goal')], max_length=20)),
                ('goal_text', models.TextField()),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='flight_map.strategy')),
            ],
            options={
                'unique_together': {('strategy', 'goal_text')},
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vision', models.TextField(blank=True, null=True)),
                ('time_horizon', models.DateField()),
                ('executive_sponsors', models.ManyToManyField(related_name='program_executive_sponsors', to=settings.AUTH_USER_MODEL)),
                ('program_leads', models.ManyToManyField(related_name='program_leads', to=settings.AUTH_USER_MODEL)),
                ('workforce_sponsors', models.ManyToManyField(related_name='program_workforce_sponsors', to=settings.AUTH_USER_MODEL)),
                ('key_improvement_targets', models.ManyToManyField(related_name='program_improvement_targets', to='flight_map.strategicgoal')),
                ('key_organizational_goals', models.ManyToManyField(related_name='program_organizational_goals', to='flight_map.strategicgoal')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='flight_map.strategy')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workstream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vision', models.TextField(blank=True, null=True)),
                ('time_horizon', models.DateField()),
                ('improvement_targets', models.JSONField(default=list)),
                ('organizational_goals', models.JSONField(default=list)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstreams', to='flight_map.program')),
                ('team_members', models.ManyToManyField(related_name='workstream_team_members', to=settings.AUTH_USER_MODEL)),
                ('workstream_leads', models.ManyToManyField(related_name='workstream_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workstream',
                'verbose_name_plural': 'Workstreams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('workstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='flight_map.workstream')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('impacted_employee_groups', models.JSONField(default=list)),
                ('change_leaders', models.JSONField(default=list)),
                ('development_support', models.JSONField(default=list)),
                ('external_resources', models.JSONField(default=list)),
                ('corporate_resources', models.JSONField(default=list)),
                ('target_start_date', models.DateField()),
                ('target_end_date', models.DateField()),
                ('parallel_activities', models.ManyToManyField(blank=True, related_name='parallel_with', to='flight_map.activity')),
                ('prerequisite_activities', models.ManyToManyField(blank=True, related_name='prerequisite_for', to='flight_map.activity')),
                ('successive_activities', models.ManyToManyField(blank=True, related_name='successor_to', to='flight_map.activity')),
                ('milestone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='flight_map.milestone')),
                ('workstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='flight_map.workstream')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['target_end_date'],
            },
        ),
    ]
