# Generated by Django 5.1.4 on 2025-02-07 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_map', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-time_horizon'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterModelOptions(
            name='roadmap',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='strategicgoal',
            options={'ordering': ['category']},
        ),
        migrations.AlterModelOptions(
            name='strategy',
            options={'ordering': ['-time_horizon'], 'verbose_name': 'Strategy', 'verbose_name_plural': 'Strategies'},
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='key_business_goals',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='key_organizational_goals',
        ),
        migrations.AddField(
            model_name='activity',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='delay_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='milestone',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='milestone',
            name='strategic_goals',
            field=models.ManyToManyField(blank=True, related_name='associated_milestones', to='flight_map.strategicgoal'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='flight_map.milestone'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='target_end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='deadline',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='time_horizon',
            field=models.DateField(db_index=True),
        ),
        migrations.CreateModel(
            name='ActivityContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='flight_map.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('activity', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MilestoneContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='flight_map.milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('milestone', 'user')},
            },
        ),
    ]
