# Generated by Django 5.1.4 on 2025-03-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='key_improvement_targets',
            field=models.ManyToManyField(blank=True, related_name='program_improvement_targets', to='flight_map.strategicgoal'),
        ),
        migrations.AlterField(
            model_name='program',
            name='key_organizational_goals',
            field=models.ManyToManyField(blank=True, related_name='program_organizational_goals', to='flight_map.strategicgoal'),
        ),
    ]
