# Generated by Django 5.1.4 on 2025-06-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_map', '0002_alter_flightmap_unique_together_flightmapdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightmap',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the flightmap was completed', null=True),
        ),
        migrations.AddField(
            model_name='flightmap',
            name='draft_id',
            field=models.IntegerField(blank=True, help_text='ID of the draft this was created from', null=True),
        ),
        migrations.AddField(
            model_name='flightmap',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Whether this flightmap is still in draft status'),
        ),
    ]
