# Generated by Django 5.1.4 on 2025-02-27 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_map', '0002_alter_program_options_alter_roadmap_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='workstream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='flight_map.workstream'),
        ),
    ]
