# Generated by Django 5.1.4 on 2025-03-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_map', '0003_alter_activity_workstream'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='dependencies',
            field=models.ManyToManyField(blank=True, help_text='Milestones that must be completed before this milestone can be achieved.', related_name='dependent_milestones', to='flight_map.milestone'),
        ),
    ]
