# Generated by Django 5.1.4 on 2025-03-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_map', '0005_activity_updated_by_milestone_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='additional_milestones',
            field=models.ManyToManyField(blank=True, help_text='Extra milestone connections (for sequential/parallel relationships).', related_name='additional_activities', to='flight_map.milestone'),
        ),
        migrations.AddField(
            model_name='activity',
            name='supported_milestones',
            field=models.ManyToManyField(blank=True, help_text='Milestones (potentially in other workstreams) that this activity supports.', related_name='supported_by_activities', to='flight_map.milestone'),
        ),
    ]
