# Generated by Django 5.1.4 on 2025-03-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_map', '0006_activity_additional_milestones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstream',
            name='color',
            field=models.CharField(default='#0000FF', max_length=7),
        ),
    ]
