# Generated by Django 5.1.4 on 2025-03-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_map', '0007_workstream_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstream',
            name='color',
            field=models.CharField(default='#22d3ee', max_length=7),
        ),
    ]
