# Generated by Django 5.1.4 on 2025-03-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_map', '0008_alter_workstream_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
