# Generated by Django 5.1.4 on 2025-03-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_map', '0009_milestone_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
