# Generated by Django 5.1.4 on 2025-03-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_map', '0010_activity_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='milestone',
            unique_together={('workstream', 'name')},
        ),
    ]
