# Generated by Django 5.1.4 on 2025-02-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.CharField(default='#3B82F6', help_text='Primary theme color (hex format)', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
